import { ProjectCta, SiteFooter, SiteHeader } from "./site-chrome";
import { pageMetadata } from "./seo";

export function generateMetadata() {
  return pageMetadata("/", "Emily Good AI | Custom Websites, Apps & Business Systems", "Launch or grow your business with custom website design, web app development, Google Workspace setup, and connected digital systems from Emily Good AI.");
}

const structuredData = {"@context":"https://schema.org","@type":"ProfessionalService",name:"Emily Good AI",url:"https://emilygoodai.com",email:"hello@emilygoodai.com",description:"Business launch services, website design, custom web apps for every industry, and Google Workspace setup.",areaServed:"Canada",priceRange:"$$$"};

export default function Home() {
  return <main>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData)}} />
    <SiteHeader />
    <section className="hero" id="top"><div className="hero-glow"/><div className="hero-copy"><p className="eyebrow"><span/> Websites, apps, and business systems</p><h1 className="hero-positioning">For founders with<br/><em>better things to do<br/>than <span className="hero-white">Troubleshoot.</span></em></h1><p className="lede">I turn your business idea into a working digital presence. You get a clear website, useful technology, and one person who understands how each piece connects.</p><div className="hero-actions"><a className="button primary" href="/contact">Let’s work together <span>↗</span></a><a className="text-link" href="/pricing">View pricing <span>→</span></a></div><p className="hero-reassurance">Clear scope · Direct collaboration · Built around your business</p></div></section>
    <div className="proof-strip"><span>STRATEGY</span><i>✦</i><span>DESIGN</span><i>✦</i><span>BUILD</span><i>✦</i><span>MANAGE</span></div>
    <section className="services home-services"><div className="section-intro"><p className="kicker">What we build</p><h2>Bring your vision online. <em>Built with intention.</em></h2><p>Start with a full launch for your business, reshape your current framework, or add features and tools to help your business grow.</p></div><div className="service-grid"><article className="service featured"><span className="num">01</span><div className="service-icon">✦</div><h3>Business Launch</h3><p>Your website, workspace, and essential business systems planned and built together.</p><a href="/pricing">View launch pricing <span>↗</span></a></article><article className="service"><span className="num">02</span><div className="service-icon">⌘</div><h3>Website Creation</h3><p>A polished, strategic website that makes your offer clear and gives visitors a reason to act.</p><a href="/pricing">View website pricing <span>↗</span></a></article><article className="service"><span className="num">03</span><div className="service-icon">◇</div><h3>Google Workspace</h3><p>Branded email and organized tools that help your team work with less friction.</p><a href="/pricing">View services + pricing <span>↗</span></a></article><article className="service"><span className="num">04</span><div className="service-icon">◎</div><h3>Custom Apps</h3><p>Custom digital products shaped around your business, users, and growth plans.</p><a href="/custom-apps">Explore custom apps <span>↗</span></a></article></div><div className="home-next"><p>Already know what you need?</p><a className="button primary" href="/pricing">View services + pricing <span>↗</span></a></div></section>
    <section className="home-process"><div><p className="kicker">How it works</p><h2>One partner from<br/><em>idea to launch.</em></h2></div><ol><li><span>01</span><div><strong>Define</strong><p>We clarify the goal, scope, audience, and technology before the build begins.</p></div></li><li><span>02</span><div><strong>Build</strong><p>I design and develop each piece around your business and keep you close to the work.</p></div></li><li><span>03</span><div><strong>Launch</strong><p>You receive a finished system, clear handoff, and the option for ongoing support.</p></div></li></ol></section>
    <ProjectCta /><SiteFooter />
  </main>;
}
