import { ProjectCta, SiteFooter, SiteHeader } from "../site-chrome";
import { pageMetadata } from "../seo";

export function generateMetadata() {
  return pageMetadata("/pricing", "Business Services & Pricing | Emily Good AI", "Explore business launch, website design, Google Workspace, ongoing care, and custom app services with clear starting prices from Emily Good AI.");
}

export default function PricingPage() {
  return <main><SiteHeader />
    <header className="page-hero"><p className="eyebrow"><span /> Services + Pricing</p><h1>Clear starting points.<br/><em>Room to scale.</em></h1><p className="lede">Explore the ways we can work together, with transparent starting prices to help you plan your next step.</p></header>
    <section className="pricing page-pricing"><div className="pricing-grid"><article className="price-card"><div className="price-top"><span>01</span><p>Landing page</p></div><h3>Focused Landing Page</h3><p className="price-note">For one offer, campaign, or new business that needs a clear path to contact or book.</p><p className="price"><small>Starting at</small><b>$2,500</b><i>CAD</i></p><ul><li>One custom page</li><li>Mobile and desktop design</li><li>On-page SEO setup</li><li>Contact or booking path</li></ul><a className="price-link" href="/contact">Discuss your landing page <span>↗</span></a></article><article className="price-card preferred"><div className="price-flag">Most requested</div><div className="price-top"><span>02</span><p>Website</p></div><h3>Business Website</h3><p className="price-note">For businesses that need a credible site with a clear path to contact or book.</p><p className="price"><small>Starting at</small><b>$3,500</b><i>CAD</i></p><ul><li>Custom responsive design</li><li>Core service pages</li><li>On-page SEO setup</li><li>Contact or booking path</li></ul><a className="price-link" href="/contact">Discuss your website <span>↗</span></a></article><article className="price-card"><div className="price-top"><span>03</span><p>Launch</p></div><h3>Business Launch</h3><p className="price-note">For a new business that needs its public presence and internal tools built together.</p><p className="price"><small>Starting at</small><b>$6,500</b><i>CAD</i></p><ul><li>Launch planning</li><li>Custom business website</li><li>Google Workspace setup</li><li>Connected client systems</li></ul><a className="price-link" href="/contact">Plan your launch <span>↗</span></a></article></div><div className="add-ons"><p><span>Google Workspace setup</span><strong>from $750 CAD</strong></p><p><span>Website care</span><strong>from $225/month</strong></p><p><span>Custom business apps</span><strong>from $9,000 CAD</strong></p></div></section>
    <section className="faq"><div className="faq-title"><p className="kicker">Common questions</p><h2>Before we<br/><em>start.</em></h2></div><div className="faq-list"><details><summary>How much does a small business website cost?<span>+</span></summary><p>A focused landing page starts at $2,500 CAD. Custom multi-page business websites start at $3,500. Larger sites receive a scope-based quote.</p></details><details><summary>Do you provide monthly support?<span>+</span></summary><p>Yes. Monthly plans can cover updates, maintenance, and support. The fee depends on the website, app, and response time you need.</p></details><details><summary>How are custom apps priced?<span>+</span></summary><p>Custom apps start at $9,000 CAD. I confirm the final investment after defining the users, features, integrations, and launch requirements.</p></details></div></section>
    <ProjectCta /><SiteFooter />
  </main>;
}
